accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("register/",views.UserRgisterView.as_view(),name="user-register"),
    path("login/",views.UserLoginView.as_view(),name="user-login"),
    path("logout/",views.UserLogoutView.as_view(),name="user-logout"),
    path("profile/<int:user_id>/",views.UserProfileView.as_view(),name="user-profile"),



    
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("index/",views.IndexView.as_view(),name="index"),
    path("deail/<int:post_id>/<slug:post_slug>/",views.PostDetailView.as_view(),name="post-detail"),
    path("delete/<int:post_id>/",views.PostDeleteView.as_view(),name="post-delete"),
    path("update/<int:post_id>/",views.PostUpdateView.as_view(),name="post-update"),
    path("create/",views.PostCreateView.as_view(),name="post-create"),



    
]

social_network/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",include("home.urls",namespace="home")),
    path("accounts/",include("accounts.urls",namespace="accounts")),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse




class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField(max_length=700)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="posts")

    def get_absolute_url(self):
        return reverse("home:post-detail",args=(self.id,self.slug))
    
class Like(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="plike")
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="ulike")

home/forms.py
from django import forms
from .models import Post


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","body")


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","body")

home/views.py
from django.shortcuts import render,redirect
from django.views import View
from .models import Post
from django.contrib import messages
from .forms import PostUpdateForm,PostCreateForm
from django.utils.text import slugify
from django.contrib.auth.mixins import LoginRequiredMixin



class IndexView(View):
    def get(self,request):
        posts = Post.objects.all()
        return render(request,"home/home.html",{
            "posts":posts
        })


class PostDetailView(View):
    def get(self,request,post_id,post_slug):
        post = Post.objects.get(pk=post_id,slug=post_slug)
        return render (request,"home/detail.html",{
            "post":post,
            
        })
    

class PostDeleteView(LoginRequiredMixin,View):

    def get(self,request,post_id):
        post = Post.objects.get(pk=post_id)
        if request.user.id == post.user.id:
            post.delete()
            messages.success(request,"your post deleted")
        else:
            messages.error(request,"you don't delete this post")
        return redirect('home:index')
    

class PostUpdateView(LoginRequiredMixin,View):
    form_class = PostUpdateForm
    template_page = "home/update.html"

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if post.user.id != request.user.id:
            messages.error(request,"you don't permmsion this post","danger")
            return redirect("home:post-detail",post.id,post.slug)
        return super().dispatch(request, *args, **kwargs)
    

    def get(self,request,post_id):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request,self.template_page,{
            "form":form,
        })
    def post(self,request,post_id):
        post = self.post_instance
        form = self.form_class(request.POST,instance=post)
        if form.is_valid():
            cd = form.cleaned_data
            new_post = form.save(commit=False)
            new_post.slug = slugify(cd["title"])
            new_post.save()
            messages.success(request,"update post is ok","success")
            return redirect("home:post-detail" ,post.id, post.slug)
        

class PostCreateView(LoginRequiredMixin,View):
    form_class = PostCreateForm
    template_page = "home/create.html"

    def get(self,request):
        form = self.form_class()
        return render(request,self.template_page,{
            "form":form,
        })

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.title = cd["title"]
            new_post.body = cd["body"]
            new_post.slug = slugify(cd["title"])
            new_post.save()
            messages.success(request,"your poast creted")
            return redirect("home:post-detail",new_post.id,new_post.slug)

home/templates/home/create.html
{% extends "base.html" %}
{% block title %}Create post{% endblock title %}
{% block content %}
    <form method="post"class="col-md-3" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock content %}

home/templates/home/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
    {% if request.user.id == post.user.id %}
        <a href={% url 'home:post-delete' post.id %} class="btn btn-danger">Delete</a>
        <a href={% url 'home:post-update' post.id %} class="btn btn-info">Update</a>

    {% endif %}
    <p>{{ post.title }}</P><br>
    <p>{{ post.body }}</P><hr><br>
    <small>
        creaed by:<a class="card-body" href="{% url 'accounts:user-profile' post.user.id %}">{{ post.user }}</a> | creaed at: {{ post.created|date:"Y M d" }}
    </small>
{% endblock content %}

home/templates/home/home.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts %}
        <a class="card-body" href="{{ post.get_absolute_url }}">{{ post.title }}</a><br>
        <small class="card-body">creaed by:<a class="card-body" href="{% url 'accounts:user-profile' post.user.id %}">{{ post.user }}</a></small><br><hr>
    {% endfor %}
{% endblock content %}

home/templates/home/update.html
{% extends "base.html" %}
{% block title %}Update post {% endblock title %}
{% block content %}
    <form method="post"class="col-md-3" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}