accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("register/",views.UserRgisterView.as_view(),name="user-register"),
    path("login/",views.UserLoginView.as_view(),name="user-login"),
    path("logout/",views.UserLogoutView.as_view(),name="user-logout"),
    path("profile/<int:user_id>/",views.UserProfileView.as_view(),name="user-profile"),



    
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("index/",views.IndexView.as_view(),name="index"),
    path("deail/<int:post_id>/<slug:post_slug>/",views.PostDetailView.as_view(),name="post-detail"),
    path("delete/<int:post_id>/",views.PostDeleteView.as_view(),name="post-delete"),
    path("update/<int:post_id>/",views.PostUpdateView.as_view(),name="post-update"),
    path("create/",views.PostCreateView.as_view(),name="post-create"),



    
]

social_network/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",include("home.urls",namespace="home")),
    path("accounts/",include("accounts.urls",namespace="accounts")),

]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</P>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="navbar-brand" aria-current="page" href="{% url 'home:index' %}">Home</a>
        </li>
        <li class="nav-item">
        {% if not request.user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'accounts:user-register' %}"> Register</a>
          <a class="navbar-brand" href="{% url 'accounts:user-login' %}"> Login</a>
          
        </li>
        {% else %}
        <li class="nav-item">
          <a class="navbar-brand" href="{% url 'accounts:user-logout' %}"> Loout</a>
          <a class="navbar-brand" href="{% url 'accounts:user-profile' request.user.id %}"> Profile</a>
        </li>
        
      </ul>
      <span class="navbar-brand">
        Hi {{ request.user.username }}
      </span>
      {% endif %}
    </div>
  </div>
</nav>





















          
        